# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d79e0fa33aa9c08a732f35623dcda51f2ecbd02443460c1036f2aa1c618c27ccd79de543368ea579828afd4732ec99933819b7c6deeb7172880e810215b982f4

test:
  secret_key_base: e3267710fed79720a7ce260ac47c64d6a6d975e7c3f60a69029f647a85a3cd9d0a7b7a1163c9b4583a1d7e1542f528f1d59abea470fed0bd2e7dcb9b22f7c779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
